spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/spring_admin_vue?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/spring_admin_vue?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: master
    password: PvaW5JMUhJ
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 20000
    #password: 123456
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s


# Qiniu 클라우드 파일 업로드 구성
qiniu:
  accessKey: gq3oE7w_8N9HMyrl7sTSlnTpGfQG2dWgIRoJJXzA
  secretKey: uW3zixlpgLypYKaWT9I_VX8EGmddVu0S5awwKtwj
  bucketName: 3b52kpcycc
  fileDomain: http://q31pcuhjc.bkt.clouddn.com
