server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: spring-restful-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# spring boot mybatis 자동 구성
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.ifsaid.shark.entity
mapper:
  identity: MYSQL
  mappers: com.ifsaid.shark.common.mapper.BaseMapper
  not-empty: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.ifsaid.shark.mapper: ERROR
    org:
      springframework:
        web:
          client:
            RestTemplate: ERROR
      mybatis:
        spring: ERROR
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari: ERROR
    root: ERROR
  file:
    path: ./log/dev


# JWT 인증 구성
jwt:
  tokenHeader: Authorization   #요청 헤더
  secret: w-eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N  #암호화 된 문자열
  expiration: 12000000    #밀리 초, 여기서 기본값은 1 시간입니다.
  tokenHead: "Bearer "


info:
  app:
    name: ${spring.application.name}
    description: spring-restful-api
    version: 2.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
